# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-07 09:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cards_num', models.CharField(max_length=16, verbose_name='Card id')),
                ('cards_pin', models.PositiveIntegerField(max_length=4, verbose_name='Card pin')),
                ('cards_success', models.PositiveIntegerField(default=4, max_length=1, verbose_name='Card success')),
                ('cards_balance', models.IntegerField(default=0, verbose_name='Card balance')),
            ],
            options={
                'ordering': ['cards_success'],
            },
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transactions_code', models.CharField(choices=[('CB', 'Check balance'), ('GM', 'Get money'), ('SS', 'Success operation')], max_length=2)),
                ('transaction_timestamp', models.TimeField(auto_now_add=True)),
                ('transaction_sum', models.CharField(default='0', max_length=255, verbose_name='Transaction sum')),
                ('transactions_link', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='card', to='cards.Cards', verbose_name='Card')),
            ],
            options={
                'ordering': ['transaction_timestamp'],
            },
        ),
    ]
