# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-07 09:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_auto_20160207_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cards',
            name='cards_pin',
            field=models.PositiveSmallIntegerField(verbose_name='Card pin'),
        ),
        migrations.AlterField(
            model_name='cards',
            name='cards_success',
            field=models.PositiveSmallIntegerField(default=4, verbose_name='Card success'),
        ),
    ]
