# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-07 09:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_auto_20160207_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='transactions_link',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card', to='cards.Cards', verbose_name='Card'),
        ),
    ]
