# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-08 15:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0005_auto_20160208_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='transaction_timestamp',
            field=models.DateTimeField(default=datetime.datetime(2016, 2, 8, 15, 38, 54, 718098)),
        ),
    ]
