# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-08 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0006_transactions_transaction_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='transaction_timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
